host: login.salesforce.com
client_secret: 1307180989195576199
client_id: 3MVG9KI2HHAq33RzJSP8zESkmV9LLciQXdw9mADUuvmuTbpHYkybXHl5O9qxOOgDlyQnkQUDgK74j1x_bo0VM
#sobject_module: SFDC_Models
debugging: true
username: matheuslucena@gmail.com
password: slayer666DT0tilUUmpLca7X5kWKGCKDf